package trading_engine

import "testing"

func TestOrderBook(t *testing.T) {
	orderBook := NewOrderBook()
	order1 := NewOrder("TEST_1", uint64(100000000), uint64(12000000000), 1, 1)

	trades1 := orderBook.Process(order1)
	if len(trades1) > 0 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", len(trades1), 0)
	}

	order2 := NewOrder("TEST_2", uint64(110000000), uint64(12000000000), 2, 1)
	trades2 := orderBook.Process(order2)
	if len(trades2) > 0 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", len(trades2), 0)
	}

	order3 := NewOrder("TEST_3", uint64(90000000), uint64(12000000000), 2, 1)
	trades3 := orderBook.Process(order3)
	if len(trades3) != 1 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", len(trades3), 1)
	} else {
		trade := trades3[0]
		if trade.Amount != 12000000000 {
			t.Errorf("Unexpected trade amount generated by order book: got %v, want %v", trade.Amount, 12000000000)
		}
		if trade.Price != 100000000 {
			t.Errorf("Unexpected trade price generated by order book: got %v, want %v", trade.Price, 100000000)
		}
	}

	orderLen := orderBook.GetMarket().Len()
	if orderLen != 1 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", orderLen, 1)
	}

	order4 := NewOrder("TEST_4", uint64(110000000), uint64(2000000000), 1, 1)
	trades4 := orderBook.Process(order4)
	if len(trades4) != 1 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", len(trades4), 1)
	} else {
		trade := trades4[0]
		if trade.Amount != 2000000000 {
			t.Errorf("Unexpected trade amount generated by order book: got %v, want %v", trade.Amount, 2000000000)
		}
		if trade.Price != 110000000 {
			t.Errorf("Unexpected trade price generated by order book: got %v, want %v", trade.Price, 110000000)
		}
	}

	order5 := NewOrder("TEST_5", uint64(111000000), uint64(12000000000), 1, 1)
	trades5 := orderBook.Process(order5)
	if len(trades5) != 1 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", len(trades5), 1)
	} else {
		trade := trades5[0]
		if trade.Amount != 10000000000 {
			t.Errorf("Unexpected trade amount generated by order book: got %v, want %v", trade.Amount, 10000000000)
		}
		if trade.Price != 110000000 {
			t.Errorf("Unexpected trade price generated by order book: got %v, want %v", trade.Price, 110000000)
		}
	}

	orderLen = orderBook.GetMarket().Len()
	if orderLen != 1 {
		t.Errorf("Unexpected trade count generated by order book: got %v, want %v", orderLen, 1)
	}

}
