// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	// Invalid status for any non set field
	EventType_Unspecified EventType = 0
	// An order has changed status, either by being acknowledged by the engine on creation,
	// being cancelled by a command or by matching with another order.
	EventType_OrderStatusChange EventType = 1
	// A new trade was generated beetween two orders
	EventType_NewTrade EventType = 2
	// A stop loss order was activated by the engine due to market change
	EventType_OrderActivated EventType = 3
)

var EventType_name = map[int32]string{
	0: "Unspecified",
	1: "OrderStatusChange",
	2: "NewTrade",
	3: "OrderActivated",
}

var EventType_value = map[string]int32{
	"Unspecified":       0,
	"OrderStatusChange": 1,
	"NewTrade":          2,
	"OrderActivated":    3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

type OrderStatusMsg struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// The type of the order: 0=limit 1=market
	Type OrderType `protobuf:"varint,2,opt,name=Type,proto3,enum=model.OrderType" json:"Type,omitempty"`
	// The side of the market: 0=buy 1=sell
	Side   MarketSide `protobuf:"varint,3,opt,name=Side,proto3,enum=model.MarketSide" json:"Side,omitempty"`
	Price  uint64     `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	Amount uint64     `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Funds  uint64     `protobuf:"varint,6,opt,name=Funds,proto3" json:"Funds,omitempty"`
	// The unique identifier the account that added the order
	OwnerID              uint64      `protobuf:"varint,7,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Status               OrderStatus `protobuf:"varint,8,opt,name=Status,proto3,enum=model.OrderStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderStatusMsg) Reset()         { *m = OrderStatusMsg{} }
func (m *OrderStatusMsg) String() string { return proto.CompactTextString(m) }
func (*OrderStatusMsg) ProtoMessage()    {}
func (*OrderStatusMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *OrderStatusMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusMsg.Unmarshal(m, b)
}
func (m *OrderStatusMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusMsg.Marshal(b, m, deterministic)
}
func (m *OrderStatusMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusMsg.Merge(m, src)
}
func (m *OrderStatusMsg) XXX_Size() int {
	return xxx_messageInfo_OrderStatusMsg.Size(m)
}
func (m *OrderStatusMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusMsg.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusMsg proto.InternalMessageInfo

func (m *OrderStatusMsg) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *OrderStatusMsg) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_Limit
}

func (m *OrderStatusMsg) GetSide() MarketSide {
	if m != nil {
		return m.Side
	}
	return MarketSide_Buy
}

func (m *OrderStatusMsg) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderStatusMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderStatusMsg) GetFunds() uint64 {
	if m != nil {
		return m.Funds
	}
	return 0
}

func (m *OrderStatusMsg) GetOwnerID() uint64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *OrderStatusMsg) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_Pending
}

type Event struct {
	Type      EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=model.EventType" json:"Type,omitempty"`
	Market    string    `protobuf:"bytes,2,opt,name=Market,proto3" json:"Market,omitempty"`
	CreatedAt int64     `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Event_OrderStatus
	//	*Event_Trade
	//	*Event_OrderActivation
	Payload              isEvent_Payload `protobuf_oneof:"Payload"`
	SeqID                uint64          `protobuf:"varint,7,opt,name=SeqID,proto3" json:"SeqID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unspecified
}

func (m *Event) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Event) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_OrderStatus struct {
	OrderStatus *OrderStatusMsg `protobuf:"bytes,4,opt,name=OrderStatus,proto3,oneof"`
}

type Event_Trade struct {
	Trade *Trade `protobuf:"bytes,5,opt,name=Trade,proto3,oneof"`
}

type Event_OrderActivation struct {
	OrderActivation *OrderStatusMsg `protobuf:"bytes,6,opt,name=OrderActivation,proto3,oneof"`
}

func (*Event_OrderStatus) isEvent_Payload() {}

func (*Event_Trade) isEvent_Payload() {}

func (*Event_OrderActivation) isEvent_Payload() {}

func (m *Event) GetPayload() isEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Event) GetOrderStatus() *OrderStatusMsg {
	if x, ok := m.GetPayload().(*Event_OrderStatus); ok {
		return x.OrderStatus
	}
	return nil
}

func (m *Event) GetTrade() *Trade {
	if x, ok := m.GetPayload().(*Event_Trade); ok {
		return x.Trade
	}
	return nil
}

func (m *Event) GetOrderActivation() *OrderStatusMsg {
	if x, ok := m.GetPayload().(*Event_OrderActivation); ok {
		return x.OrderActivation
	}
	return nil
}

func (m *Event) GetSeqID() uint64 {
	if m != nil {
		return m.SeqID
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_OrderStatus)(nil),
		(*Event_Trade)(nil),
		(*Event_OrderActivation)(nil),
	}
}

type Events struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.EventType", EventType_name, EventType_value)
	proto.RegisterType((*OrderStatusMsg)(nil), "model.OrderStatusMsg")
	proto.RegisterType((*Event)(nil), "model.Event")
	proto.RegisterType((*Events)(nil), "model.Events")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xd2, 0x26, 0x5d, 0x5f, 0xa6, 0x2e, 0x7b, 0x62, 0x93, 0x35, 0x71, 0xa8, 0xaa, 0x21,
	0x4d, 0x3b, 0xf4, 0x50, 0x4e, 0x1c, 0xc3, 0x0a, 0x5a, 0x0f, 0x65, 0x93, 0xbb, 0xfd, 0x01, 0xa6,
	0x7e, 0x94, 0x88, 0x2d, 0x29, 0x8e, 0xbb, 0xa9, 0xff, 0x11, 0xff, 0x21, 0x57, 0xe4, 0x67, 0x53,
	0x02, 0x48, 0xbb, 0xf5, 0xfb, 0xe1, 0xf8, 0xfb, 0xbe, 0x1a, 0x32, 0x7a, 0xa2, 0xca, 0x4e, 0x36,
	0xa6, 0xb6, 0x35, 0x26, 0x8f, 0xb5, 0xa6, 0x87, 0xb3, 0xac, 0x36, 0x9a, 0x8c, 0xe7, 0xce, 0x32,
	0x6b, 0x94, 0x26, 0x0f, 0xc6, 0x3f, 0x23, 0x18, 0xde, 0x38, 0x71, 0x69, 0x95, 0xdd, 0x36, 0x8b,
	0x66, 0x8d, 0x43, 0x88, 0xe7, 0x33, 0x11, 0x8d, 0xa2, 0x8b, 0x9e, 0x8c, 0xe7, 0x33, 0x3c, 0x87,
	0xde, 0xdd, 0x6e, 0x43, 0x22, 0x1e, 0x45, 0x17, 0xc3, 0x69, 0x3e, 0xe1, 0x4f, 0x4e, 0xf8, 0x90,
	0xe3, 0x25, 0xab, 0xf8, 0x06, 0x7a, 0xcb, 0x52, 0x93, 0xe8, 0xb2, 0xeb, 0x38, 0xb8, 0x16, 0xca,
	0x7c, 0x23, 0xeb, 0x04, 0xc9, 0x32, 0xbe, 0x82, 0xe4, 0xd6, 0x94, 0x2b, 0x12, 0x3d, 0xfe, 0xbe,
	0x07, 0x78, 0x0a, 0x69, 0xf1, 0x58, 0x6f, 0x2b, 0x2b, 0x12, 0xa6, 0x03, 0x72, 0xee, 0x8f, 0xdb,
	0x4a, 0x37, 0x22, 0xf5, 0x6e, 0x06, 0x28, 0xa0, 0x7f, 0xf3, 0x5c, 0x91, 0x99, 0xcf, 0x44, 0x9f,
	0xf9, 0xdf, 0x10, 0x2f, 0x21, 0xf5, 0x3d, 0xc4, 0x01, 0xc7, 0xc0, 0x76, 0x58, 0xaf, 0xc8, 0xe0,
	0x18, 0xff, 0x88, 0x21, 0xf9, 0xe0, 0xa6, 0xda, 0x17, 0x8c, 0xfe, 0x2a, 0xc8, 0x5a, 0xab, 0xe0,
	0x29, 0xa4, 0xbe, 0x0d, 0x0f, 0x31, 0x90, 0x01, 0xe1, 0x6b, 0x18, 0x5c, 0x19, 0x52, 0x96, 0x74,
	0x61, 0xb9, 0x7d, 0x57, 0xfe, 0x21, 0xf0, 0x1d, 0x64, 0xad, 0xcb, 0xb9, 0x75, 0x36, 0x3d, 0xf9,
	0x3f, 0xd6, 0xa2, 0x59, 0x5f, 0x77, 0x64, 0xdb, 0x8b, 0xe7, 0x90, 0xdc, 0xb9, 0x7f, 0x8a, 0x37,
	0xc9, 0xa6, 0x87, 0xe1, 0x10, 0x73, 0xd7, 0x1d, 0xe9, 0x45, 0x2c, 0xe0, 0x88, 0x0f, 0x15, 0x2b,
	0x5b, 0x3e, 0x29, 0x5b, 0xd6, 0x15, 0x8f, 0xf5, 0xc2, 0x25, 0xff, 0xfa, 0xdd, 0xca, 0x4b, 0xfa,
	0xbe, 0x5f, 0xd3, 0x83, 0xf7, 0x03, 0xe8, 0xdf, 0xaa, 0xdd, 0x43, 0xad, 0xf4, 0x78, 0x02, 0x29,
	0xaf, 0xe1, 0x32, 0x85, 0x5f, 0x22, 0x1a, 0x75, 0x5b, 0xa1, 0x98, 0x94, 0x41, 0xbb, 0xbc, 0x87,
	0xc1, 0x7e, 0x3d, 0x3c, 0x82, 0xec, 0xbe, 0x6a, 0x36, 0xb4, 0x2a, 0xbf, 0x94, 0xa4, 0xf3, 0x0e,
	0x9e, 0xc0, 0x71, 0x2b, 0xd3, 0xd5, 0x57, 0x55, 0xad, 0x29, 0x8f, 0xf0, 0x10, 0x0e, 0x3e, 0xd1,
	0x33, 0x97, 0xca, 0x63, 0xc4, 0xf0, 0x2c, 0x43, 0x4c, 0xd2, 0x79, 0xf7, 0x73, 0xca, 0x4f, 0xf6,
	0xed, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0xb3, 0xb1, 0x03, 0xe2, 0x02, 0x00, 0x00,
}
