// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	// Invalid status for any non set field
	EventType_Unspecified EventType = 0
	// An order has changed status, either by being acknowledged by the engine on creation,
	// being cancelled by a command or by matching with another order.
	EventType_OrderStatusChange EventType = 1
	// A new trade was generated beetween two orders
	EventType_NewTrade EventType = 2
	// A stop loss order was activated by the engine due to market change
	EventType_OrderActivated EventType = 3
)

var EventType_name = map[int32]string{
	0: "Unspecified",
	1: "OrderStatusChange",
	2: "NewTrade",
	3: "OrderActivated",
}
var EventType_value = map[string]int32{
	"Unspecified":       0,
	"OrderStatusChange": 1,
	"NewTrade":          2,
	"OrderActivated":    3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_cc44a737018b77a5, []int{0}
}

type OrderStatusMsg struct {
	ID                   uint64      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Amount               uint64      `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Funds                uint64      `protobuf:"varint,3,opt,name=Funds,proto3" json:"Funds,omitempty"`
	Status               OrderStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=model.OrderStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderStatusMsg) Reset()         { *m = OrderStatusMsg{} }
func (m *OrderStatusMsg) String() string { return proto.CompactTextString(m) }
func (*OrderStatusMsg) ProtoMessage()    {}
func (*OrderStatusMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_cc44a737018b77a5, []int{0}
}
func (m *OrderStatusMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusMsg.Unmarshal(m, b)
}
func (m *OrderStatusMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusMsg.Marshal(b, m, deterministic)
}
func (dst *OrderStatusMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusMsg.Merge(dst, src)
}
func (m *OrderStatusMsg) XXX_Size() int {
	return xxx_messageInfo_OrderStatusMsg.Size(m)
}
func (m *OrderStatusMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusMsg.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusMsg proto.InternalMessageInfo

func (m *OrderStatusMsg) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *OrderStatusMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderStatusMsg) GetFunds() uint64 {
	if m != nil {
		return m.Funds
	}
	return 0
}

func (m *OrderStatusMsg) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_Pending
}

type Event struct {
	Type EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=model.EventType" json:"Type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Event_OrderStatus
	//	*Event_Trade
	Payload              isEvent_Payload `protobuf_oneof:"Payload"`
	CreatedAt            int64           `protobuf:"varint,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_cc44a737018b77a5, []int{1}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unspecified
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_OrderStatus struct {
	OrderStatus *OrderStatusMsg `protobuf:"bytes,2,opt,name=OrderStatus,proto3,oneof"`
}

type Event_Trade struct {
	Trade *Trade `protobuf:"bytes,3,opt,name=Trade,proto3,oneof"`
}

func (*Event_OrderStatus) isEvent_Payload() {}

func (*Event_Trade) isEvent_Payload() {}

func (m *Event) GetPayload() isEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Event) GetOrderStatus() *OrderStatusMsg {
	if x, ok := m.GetPayload().(*Event_OrderStatus); ok {
		return x.OrderStatus
	}
	return nil
}

func (m *Event) GetTrade() *Trade {
	if x, ok := m.GetPayload().(*Event_Trade); ok {
		return x.Trade
	}
	return nil
}

func (m *Event) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_OrderStatus)(nil),
		(*Event_Trade)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// Payload
	switch x := m.Payload.(type) {
	case *Event_OrderStatus:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrderStatus); err != nil {
			return err
		}
	case *Event_Trade:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Trade); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Payload has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 2: // Payload.OrderStatus
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OrderStatusMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Event_OrderStatus{msg}
		return true, err
	case 3: // Payload.Trade
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Trade)
		err := b.DecodeMessage(msg)
		m.Payload = &Event_Trade{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// Payload
	switch x := m.Payload.(type) {
	case *Event_OrderStatus:
		s := proto.Size(x.OrderStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Trade:
		s := proto.Size(x.Trade)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*OrderStatusMsg)(nil), "model.OrderStatusMsg")
	proto.RegisterType((*Event)(nil), "model.Event")
	proto.RegisterEnum("model.EventType", EventType_name, EventType_value)
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_cc44a737018b77a5) }

var fileDescriptor_event_cc44a737018b77a5 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xd9, 0x42, 0xd1, 0xce, 0x92, 0x5a, 0x27, 0x62, 0x1a, 0xe2, 0x81, 0x10, 0x0e, 0x84,
	0x03, 0x87, 0x7a, 0xf2, 0x88, 0xa0, 0x81, 0x03, 0x6a, 0x56, 0xf8, 0x01, 0x2b, 0x3b, 0x22, 0x09,
	0x74, 0x49, 0xbb, 0xc5, 0xe0, 0x1f, 0xf3, 0xef, 0x99, 0x6e, 0x1b, 0x6d, 0xe2, 0xf1, 0xbd, 0x37,
	0x33, 0xdf, 0x6b, 0x17, 0x38, 0x1d, 0x29, 0x36, 0xa3, 0x43, 0xa2, 0x8d, 0x46, 0x77, 0xaf, 0x15,
	0xed, 0x3a, 0x5c, 0x27, 0x8a, 0x92, 0xc2, 0xeb, 0x70, 0x93, 0x48, 0x45, 0x85, 0xe8, 0x7d, 0x81,
	0xff, 0x9c, 0x67, 0xaf, 0x46, 0x9a, 0x2c, 0x5d, 0xa4, 0x1b, 0xf4, 0xc1, 0x99, 0x4f, 0x43, 0xd6,
	0x65, 0x83, 0x86, 0x70, 0xe6, 0x53, 0xbc, 0x86, 0xe6, 0x78, 0xaf, 0xb3, 0xd8, 0x84, 0x8e, 0xf5,
	0x4a, 0x85, 0x57, 0xe0, 0x3e, 0x66, 0xb1, 0x4a, 0xc3, 0xba, 0xb5, 0x0b, 0x81, 0x43, 0x68, 0x16,
	0xa7, 0xc2, 0x46, 0x97, 0x0d, 0xfc, 0x08, 0x47, 0xb6, 0xc1, 0xa8, 0x02, 0x11, 0xe5, 0x44, 0xef,
	0x9b, 0x81, 0xfb, 0x90, 0x97, 0xc5, 0x3e, 0x34, 0x96, 0xa7, 0x03, 0x59, 0xaa, 0x1f, 0x05, 0xe5,
	0x8e, 0xcd, 0x72, 0x5f, 0xd8, 0x14, 0xef, 0x80, 0x57, 0xce, 0xd8, 0x3a, 0x3c, 0x6a, 0xff, 0x07,
	0x2c, 0xd2, 0xcd, 0xac, 0x26, 0xaa, 0xb3, 0xd8, 0x07, 0x77, 0x99, 0x7f, 0xb5, 0x2d, 0xcb, 0xa3,
	0x56, 0xb9, 0x64, 0xbd, 0x59, 0x4d, 0x14, 0x21, 0xde, 0x80, 0x37, 0x49, 0x48, 0x1a, 0x52, 0x63,
	0x13, 0x7a, 0x5d, 0x36, 0xa8, 0x8b, 0x3f, 0xe3, 0xde, 0x83, 0xb3, 0x17, 0x79, 0xda, 0x69, 0xa9,
	0x86, 0x2b, 0xf0, 0x7e, 0xcb, 0xe1, 0x05, 0xf0, 0x55, 0x9c, 0x1e, 0x68, 0xbd, 0x7d, 0xdf, 0x92,
	0x0a, 0x6a, 0xd8, 0x86, 0xcb, 0x0a, 0x7b, 0xf2, 0x21, 0xe3, 0x0d, 0x05, 0x0c, 0x5b, 0x70, 0xfe,
	0x44, 0x9f, 0x96, 0x14, 0x38, 0x88, 0xe5, 0x8f, 0x1f, 0xaf, 0xcd, 0xf6, 0x98, 0x13, 0x82, 0xfa,
	0x5b, 0xd3, 0xbe, 0xc9, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x1f, 0x01, 0x54, 0xc3,
	0x01, 0x00, 0x00,
}
