// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trade struct {
	Price                uint64     `protobuf:"varint,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Amount               uint64     `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	AskID                uint64     `protobuf:"varint,3,opt,name=AskID,proto3" json:"AskID,omitempty"`
	AskOwnerID           uint64     `protobuf:"varint,4,opt,name=AskOwnerID,proto3" json:"AskOwnerID,omitempty"`
	BidID                uint64     `protobuf:"varint,5,opt,name=BidID,proto3" json:"BidID,omitempty"`
	BidOwnerID           uint64     `protobuf:"varint,6,opt,name=BidOwnerID,proto3" json:"BidOwnerID,omitempty"`
	TakerSide            MarketSide `protobuf:"varint,7,opt,name=TakerSide,proto3,enum=model.MarketSide" json:"TakerSide,omitempty"`
	SeqID                uint64     `protobuf:"varint,8,opt,name=SeqID,proto3" json:"SeqID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee944bd90e8a0312, []int{0}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetAskID() uint64 {
	if m != nil {
		return m.AskID
	}
	return 0
}

func (m *Trade) GetAskOwnerID() uint64 {
	if m != nil {
		return m.AskOwnerID
	}
	return 0
}

func (m *Trade) GetBidID() uint64 {
	if m != nil {
		return m.BidID
	}
	return 0
}

func (m *Trade) GetBidOwnerID() uint64 {
	if m != nil {
		return m.BidOwnerID
	}
	return 0
}

func (m *Trade) GetTakerSide() MarketSide {
	if m != nil {
		return m.TakerSide
	}
	return MarketSide_Buy
}

func (m *Trade) GetSeqID() uint64 {
	if m != nil {
		return m.SeqID
	}
	return 0
}

func init() {
	proto.RegisterType((*Trade)(nil), "model.Trade")
}

func init() { proto.RegisterFile("trade.proto", fileDescriptor_ee944bd90e8a0312) }

var fileDescriptor_ee944bd90e8a0312 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4a, 0x4c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x91, 0xe2,
	0xce, 0x2f, 0x4a, 0x49, 0x2d, 0x82, 0x88, 0x29, 0xbd, 0x60, 0xe4, 0x62, 0x0d, 0x01, 0xa9, 0x11,
	0x12, 0xe1, 0x62, 0x0d, 0x28, 0xca, 0x4c, 0x4e, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82,
	0x70, 0x84, 0xc4, 0xb8, 0xd8, 0x1c, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98, 0xc0, 0xc2, 0x50,
	0x1e, 0x48, 0xb5, 0x63, 0x71, 0xb6, 0xa7, 0x8b, 0x04, 0x33, 0x44, 0x35, 0x98, 0x23, 0x24, 0xc7,
	0xc5, 0xe5, 0x58, 0x9c, 0xed, 0x5f, 0x9e, 0x97, 0x5a, 0xe4, 0xe9, 0x22, 0xc1, 0x02, 0x96, 0x42,
	0x12, 0x01, 0xe9, 0x72, 0xca, 0x4c, 0xf1, 0x74, 0x91, 0x60, 0x85, 0xe8, 0x02, 0x73, 0x40, 0xba,
	0x9c, 0x32, 0x53, 0x60, 0xba, 0xd8, 0x20, 0xba, 0x10, 0x22, 0x42, 0xfa, 0x5c, 0x9c, 0x21, 0x89,
	0xd9, 0xa9, 0x45, 0xc1, 0x99, 0x29, 0xa9, 0x12, 0xec, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x82, 0x7a,
	0x60, 0xbf, 0xe8, 0xf9, 0x26, 0x16, 0x65, 0xa7, 0x96, 0x80, 0x24, 0x82, 0x10, 0x6a, 0x40, 0xd6,
	0x04, 0xa7, 0x16, 0x7a, 0xba, 0x48, 0x70, 0x40, 0xac, 0x01, 0x73, 0x92, 0xd8, 0xc0, 0x3e, 0x36,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xb7, 0xa1, 0xc5, 0x14, 0x01, 0x00, 0x00,
}
