server: 
  monitoring: 
    enabled: true
    host: 0.0.0.0
    port: 6060

markets:
  btcusd:
    market_id: btcusd
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/btcusd.dat
    listen: 
      broker: requests
      topic: engine.orders.btcusd
    publish: 
      broker: events
      topic: engine.events.btcusd
    stats:
      broker: stats
      topic: engine.stats.btcusd
  ethusd:
    market_id: ethusd
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ethusd.dat
    listen: 
      broker: requests
      topic: engine.orders.ethusd
    publish: 
      broker: events
      topic: engine.events.ethusd
    stats:
      broker: stats
      topic: engine.stats.ethusd

brokers:
  consumers:
    requests: 
      name: matching_engine_test
      hosts: 
        - kafka:9092
      topics:
        - engine.orders.btcusd
        - engine.orders.ethusd
  producers:
    events: 
      hosts: 
        - kafka:9092
      topics: 
        - engine.events.btcusd
        - engine.events.ethusd
    stats: 
      hosts: 
        - kafka:9092
      topics: 
        - engine.stats.btcusd
        - engine.stats.ethusd
