version: '3.2'
services:
  # Kafka Cluster with Zookeeper
  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - /root/hashiru_engine/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana:/var/lib/grafana
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "209.97.180.83"
      # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      HOSTNAME_COMMAND: "echo '209.97.180.83'"
      KAFKA_CREATE_TOPICS: engine.orders.btc.usd:1:1,engine.orders.eth.usd:1:1,engine.events.btc.usd:3:1,engine.events.eth.usd:3:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS_PER_TOPIC: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  hashiru_engine:
    build:
      context: ../
    restart: always
    ports:
      - 6060:6060
    image: hashiru_engine:local
    volumes:
      - backups:/root/backups
      - /root/hashiru_engine/.engine.yml:/root/.engine.yml
  # Debug: Kafka Manager
  kafka_manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    restart: always
volumes:
  grafana:
  backups:
