version: '3.2'
services:
  # Kafka Cluster with Zookeeper
  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - /root/trading_engine/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana:/var/lib/grafana
volumes:
  grafana:
