server:
  debug: true
  monitoring: 
    enabled: true
    host: 0.0.0.0
    port: 6060

markets:
  ltcbtc:
    market_id: ltcbtc
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ltcbtc.dat
    listen: 
      broker: requests
      topic: engine.orders.ltcbtc
    publish: 
      broker: events
      topic: engine.events.ltcbtc
  ethbtc:
    market_id: ethbtc
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ethbtc.dat
    listen: 
      broker: requests
      topic: engine.orders.ethbtc
    publish: 
      broker: events
      topic: engine.events.ethbtc
  xrpbtc:
    market_id: xrpbtc
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/xrpbtc.dat
    listen: 
      broker: requests
      topic: engine.orders.xrpbtc
    publish: 
      broker: events
      topic: engine.events.xrpbtc
  bchbtc:
    market_id: bchbtc
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/bchbtc.dat
    listen: 
      broker: requests
      topic: engine.orders.bchbtc
    publish: 
      broker: events
      topic: engine.events.bchbtc
  prdxbtc:
    market_id: prdxbtc
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/prdxbtc.dat
    listen: 
      broker: requests
      topic: engine.orders.prdxbtc
    publish: 
      broker: events
      topic: engine.events.prdxbtc
  ltceth:
    market_id: ltceth
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ltceth.dat
    listen: 
      broker: requests
      topic: engine.orders.ltceth
    publish: 
      broker: events
      topic: engine.events.ltceth
  xrpeth:
    market_id: xrpeth
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/xrpeth.dat
    listen: 
      broker: requests
      topic: engine.orders.xrpeth
    publish: 
      broker: events
      topic: engine.events.xrpeth
  eoseth:
    market_id: eoseth
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/eoseth.dat
    listen: 
      broker: requests
      topic: engine.orders.eoseth
    publish: 
      broker: events
      topic: engine.events.eoseth
  prdxeth:
    market_id: prdxeth
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/prdxeth.dat
    listen: 
      broker: requests
      topic: engine.orders.prdxeth
    publish: 
      broker: events
      topic: engine.events.prdxeth
  btcusdt:
    market_id: btcusdt
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/btcusdt.dat
    listen: 
      broker: requests
      topic: engine.orders.btcusdt
    publish: 
      broker: events
      topic: engine.events.btcusdt
  ethusdt:
    market_id: ethusdt
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ethusdt.dat
    listen: 
      broker: requests
      topic: engine.orders.ethusdt
    publish: 
      broker: events
      topic: engine.events.ethusdt
  ltcusdt:
    market_id: ltcusdt
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ltcusdt.dat
    listen: 
      broker: requests
      topic: engine.orders.ltcusdt
    publish: 
      broker: events
      topic: engine.events.ltcusdt
  bchusdt:
    market_id: bchusdt
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/bchusdt.dat
    listen: 
      broker: requests
      topic: engine.orders.bchusdt
    publish: 
      broker: events
      topic: engine.events.bchusdt
  prdxusdt:
    market_id: prdxusdt
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/prdxusdt.dat
    listen: 
      broker: requests
      topic: engine.orders.prdxusdt
    publish: 
      broker: events
      topic: engine.events.prdxusdt
  ltcprdx:
    market_id: ltcprdx
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/ltcprdx.dat
    listen: 
      broker: requests
      topic: engine.orders.ltcprdx
    publish: 
      broker: events
      topic: engine.events.ltcprdx
  xrpprdx:
    market_id: xrpprdx
    price_precision: 8
    volume_precision: 8
    quote_increments: 0.01 # not used yet
    base_min: 0.0001 # not used yet
    base_max: 10000 # not used yet
    backup:
      interval: 1
      path: /root/backups/xrpprdx.dat
    listen: 
      broker: requests
      topic: engine.orders.xrpprdx
    publish: 
      broker: events
      topic: engine.events.xrpprdx

brokers:
  consumers:
    requests: 
      hosts: 
        - kafka:9092
  producers:
    events: 
      hosts: 
        - kafka:9092