FROM golang:1.12.7 as build
RUN mkdir -p /build/matching-engine
WORKDIR /build/matching-engine/

# Force the go compiler to use modules
ENV GO111MODULE=on

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
# COPY go.sum .

# This is the ‘magic’ step that will download all the dependencies that are specified in 
# the go.mod and go.sum file.
# Because of how the layer caching system works in Docker, the  go mod download 
# command will _ only_ be re-run when the go.mod or go.sum file change 
# (or when we add another docker instruction below this line)
RUN go mod download

# Add code refresh package
RUN go get github.com/cespare/reflex
RUN echo "-r '(\.go$|go\.mod)' -s -- sh -c 'go run . server'" >> /reflex.conf
ENTRYPOINT ["reflex", "--decoration=none", "-c", "/reflex.conf"]
 
COPY . .

# RUN CGO_ENABLED=0 go build -a -installsuffix cgo --ldflags "-s -w" -o /usr/bin/matching_engine

EXPOSE 6060