version: '3.2'
services:
  # Kafka Cluster with Zookeeper
  prometheus: 
    image: quay.io/prometheus/prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    restart: always
    volumes:
      - grafana:/var/lib/grafana
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      HOSTNAME_COMMAND: "echo 'kafka'"
      KAFKA_CREATE_TOPICS: trading.order.btc.eth:1:1,trading.trade.btc.eth:3:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS_PER_TOPIC: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  trading_engine:
    build: 
      context: .
    restart: always
    ports: 
      - 6060:6060
    image: trading_engine:local
    
  # kafka_second:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9093:9092"
  #   restart: always
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka_second
  #     # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
  #     HOSTNAME_COMMAND: "echo 'kafka_second'"
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  # kafka_third:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9094:9092"
  #   restart: always
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka_third
  #     # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
  #     HOSTNAME_COMMAND: "echo 'kafka_third'"
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  # Debug: Kafka Manager
  kafka_manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    restart: always
volumes:
  grafana: