// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book_entry.proto

package engine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookEntry struct {
	Price                uint64   `protobuf:"varint,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Order                *Order   `protobuf:"bytes,3,opt,name=Order,proto3" json:"Order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookEntry) Reset()         { *m = BookEntry{} }
func (m *BookEntry) String() string { return proto.CompactTextString(m) }
func (*BookEntry) ProtoMessage()    {}
func (*BookEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_bced1c6750940dfc, []int{0}
}

func (m *BookEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookEntry.Unmarshal(m, b)
}
func (m *BookEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookEntry.Marshal(b, m, deterministic)
}
func (m *BookEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookEntry.Merge(m, src)
}
func (m *BookEntry) XXX_Size() int {
	return xxx_messageInfo_BookEntry.Size(m)
}
func (m *BookEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BookEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BookEntry proto.InternalMessageInfo

func (m *BookEntry) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BookEntry) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BookEntry) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterType((*BookEntry)(nil), "engine.BookEntry")
}

func init() { proto.RegisterFile("book_entry.proto", fileDescriptor_bced1c6750940dfc) }

var fileDescriptor_bced1c6750940dfc = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xca, 0xcf, 0xcf,
	0x8e, 0x4f, 0xcd, 0x2b, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcd,
	0x4b, 0xcf, 0xcc, 0x4b, 0x95, 0xe2, 0xce, 0x2f, 0x4a, 0x49, 0x2d, 0x82, 0x08, 0x2a, 0xc5, 0x71,
	0x71, 0x3a, 0xe5, 0xe7, 0x67, 0xbb, 0x82, 0xd4, 0x09, 0x89, 0x70, 0xb1, 0x06, 0x14, 0x65, 0x26,
	0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0x8e, 0xb9,
	0xf9, 0xa5, 0x79, 0x25, 0x12, 0x4c, 0x60, 0x61, 0x28, 0x4f, 0x48, 0x99, 0x8b, 0xd5, 0x1f, 0x64,
	0x92, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0xaf, 0x1e, 0xc4, 0x7c, 0x3d, 0xb0, 0x60, 0x10,
	0x44, 0x2e, 0x89, 0x0d, 0x6c, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x18, 0x31, 0x0c,
	0x8f, 0x00, 0x00, 0x00,
}
