package engine

import (
	"github.com/segmentio/kafka-go"
	"gitlab.com/around25/products/matching-engine/model"
)

// Event structure for order execution
type Event struct {
	Msg    kafka.Message
	Order  model.Order
	Events []model.Event
}

// NewEvent Create a new event
func NewEvent(msg kafka.Message) Event {
	return Event{Msg: msg}
}

// Decode the contained message into a proper order
func (event *Event) Decode() {
	event.Order.FromBinary(event.Msg.Value)
}

// SetEvents - sets the generated events from that order on the current market
func (event *Event) SetEvents(events []model.Event) {
	event.Events = events
}

// HasEvents checks if there are any events generated by the order.
// @deprecated should always be true since the order is acknowledged
func (event Event) HasEvents() bool {
	return len(event.Events) > 0
}
