// Code generated by protoc-gen-go. DO NOT EDIT.
// source: market.proto

package engine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MarketBackup struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition            int32    `protobuf:"varint,2,opt,name=Partition,proto3" json:"Partition,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	LowestAsk            uint64   `protobuf:"varint,4,opt,name=LowestAsk,proto3" json:"LowestAsk,omitempty"`
	HighestBid           uint64   `protobuf:"varint,5,opt,name=HighestBid,proto3" json:"HighestBid,omitempty"`
	BuyOrders            []*Order `protobuf:"bytes,6,rep,name=BuyOrders,proto3" json:"BuyOrders,omitempty"`
	SellOrders           []*Order `protobuf:"bytes,7,rep,name=SellOrders,proto3" json:"SellOrders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketBackup) Reset()         { *m = MarketBackup{} }
func (m *MarketBackup) String() string { return proto.CompactTextString(m) }
func (*MarketBackup) ProtoMessage()    {}
func (*MarketBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{0}
}

func (m *MarketBackup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketBackup.Unmarshal(m, b)
}
func (m *MarketBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketBackup.Marshal(b, m, deterministic)
}
func (m *MarketBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketBackup.Merge(m, src)
}
func (m *MarketBackup) XXX_Size() int {
	return xxx_messageInfo_MarketBackup.Size(m)
}
func (m *MarketBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketBackup.DiscardUnknown(m)
}

var xxx_messageInfo_MarketBackup proto.InternalMessageInfo

func (m *MarketBackup) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MarketBackup) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *MarketBackup) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MarketBackup) GetLowestAsk() uint64 {
	if m != nil {
		return m.LowestAsk
	}
	return 0
}

func (m *MarketBackup) GetHighestBid() uint64 {
	if m != nil {
		return m.HighestBid
	}
	return 0
}

func (m *MarketBackup) GetBuyOrders() []*Order {
	if m != nil {
		return m.BuyOrders
	}
	return nil
}

func (m *MarketBackup) GetSellOrders() []*Order {
	if m != nil {
		return m.SellOrders
	}
	return nil
}

func init() {
	proto.RegisterType((*MarketBackup)(nil), "engine.MarketBackup")
}

func init() { proto.RegisterFile("market.proto", fileDescriptor_3f90997f23a2c3f8) }

var fileDescriptor_3f90997f23a2c3f8 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0x86, 0x40,
	0x14, 0x85, 0x99, 0xfc, 0x9d, 0xf0, 0xfe, 0xb6, 0x19, 0x22, 0x86, 0x88, 0x18, 0x5a, 0x0d, 0x44,
	0x2e, 0xea, 0x09, 0x72, 0xd5, 0xa2, 0x30, 0xa6, 0x5e, 0xc0, 0xf4, 0x6a, 0x83, 0xe6, 0xc8, 0xcc,
	0x48, 0xf4, 0xde, 0x3d, 0x40, 0x38, 0x0a, 0xba, 0x68, 0x79, 0xbe, 0xf3, 0x5d, 0xb8, 0x07, 0xd2,
	0xaf, 0xd2, 0x76, 0xe8, 0xb3, 0xd1, 0x1a, 0x6f, 0x18, 0xc5, 0xa1, 0xd5, 0x03, 0x5e, 0x1e, 0x8d,
	0xad, 0xd1, 0x2e, 0xf0, 0xe6, 0x97, 0x40, 0xfa, 0x12, 0xac, 0xbc, 0xac, 0xba, 0x69, 0x64, 0xe7,
	0x10, 0xbf, 0x9b, 0x51, 0x57, 0x9c, 0x08, 0x22, 0x13, 0xb5, 0x04, 0x76, 0x05, 0xc9, 0x6b, 0x69,
	0xbd, 0xf6, 0xda, 0x0c, 0xfc, 0x44, 0x10, 0x19, 0xab, 0x0d, 0xb0, 0x0b, 0xa0, 0x45, 0xd3, 0x38,
	0xf4, 0x3c, 0x12, 0x44, 0x46, 0x6a, 0x4d, 0xf3, 0xd5, 0xb3, 0xf9, 0x46, 0xe7, 0x1f, 0x5d, 0xc7,
	0x0f, 0x82, 0xc8, 0x83, 0xda, 0x00, 0xbb, 0x06, 0x78, 0xd2, 0xed, 0x27, 0x3a, 0x9f, 0xeb, 0x9a,
	0xc7, 0xa1, 0xde, 0x11, 0x76, 0x0b, 0x49, 0x3e, 0xfd, 0x14, 0xf3, 0xb3, 0x8e, 0x53, 0x11, 0xc9,
	0xe3, 0xfd, 0x59, 0xb6, 0x6c, 0xc8, 0x02, 0x55, 0x5b, 0xcf, 0xee, 0x00, 0xde, 0xb0, 0xef, 0x57,
	0xfb, 0xf4, 0x3f, 0x7b, 0x27, 0x7c, 0xd0, 0xb0, 0xfe, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x1e,
	0x0d, 0x66, 0x7d, 0x22, 0x01, 0x00, 0x00,
}
