// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade.proto

package engine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trade struct {
	Price                uint64   `protobuf:"varint,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	TakerOrderID         string   `protobuf:"bytes,3,opt,name=TakerOrderID,proto3" json:"TakerOrderID,omitempty"`
	MakerOrderID         string   `protobuf:"bytes,4,opt,name=MakerOrderID,proto3" json:"MakerOrderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee944bd90e8a0312, []int{0}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetTakerOrderID() string {
	if m != nil {
		return m.TakerOrderID
	}
	return ""
}

func (m *Trade) GetMakerOrderID() string {
	if m != nil {
		return m.MakerOrderID
	}
	return ""
}

func init() {
	proto.RegisterType((*Trade)(nil), "engine.Trade")
}

func init() { proto.RegisterFile("trade.proto", fileDescriptor_ee944bd90e8a0312) }

var fileDescriptor_ee944bd90e8a0312 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4a, 0x4c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0x55,
	0xaa, 0xe5, 0x62, 0x0d, 0x01, 0x09, 0x0b, 0x89, 0x70, 0xb1, 0x06, 0x14, 0x65, 0x26, 0xa7, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0x8e, 0xb9, 0xf9, 0xa5,
	0x79, 0x25, 0x12, 0x4c, 0x60, 0x61, 0x28, 0x4f, 0x48, 0x89, 0x8b, 0x27, 0x24, 0x31, 0x3b, 0xb5,
	0xc8, 0xbf, 0x28, 0x25, 0xb5, 0xc8, 0xd3, 0x45, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0x45,
	0x0c, 0xa4, 0xc6, 0x17, 0x59, 0x0d, 0x0b, 0x44, 0x0d, 0xb2, 0x58, 0x12, 0x1b, 0xd8, 0x35, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x3a, 0xfe, 0x24, 0x9c, 0x00, 0x00, 0x00,
}
