{
 "title": "Main Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*avg(rate(go_memstats_alloc_bytes_total{}[10s]))/sum(engine_daemon_engine_memory_bytes{job=\"docker\"})"
    },
    {}
   ]
  },
  {
   "title": "Orders/Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_order_count{}[1m]))"
    }
   ]
  },
  {
   "title": "Trades/Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(engine_trade_count{}[1m]))"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "go_threads{}" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{job=\"trading-engine\"}"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "engine_message_queue_count{}" }
   ]
  },
  {
   "title": "Queued Orders",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "engine_order_queue_count{}" }
   ]
  },
  {
   "title": "Queued Trades",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "engine_trade_queue_count" }
   ]
  },
  {
   "title": "go_memstats_gc_cpu_fraction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction{}" }
   ]
  },
  {
   "title": "go_memstats_stack_sys_bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_stack_sys_bytes{}" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes{}" }
   ]
  }
 ]
}